### ISSUE TITLE
Rotate Gizmo not working on Jammy

### ISSUE THREAD

**Issue by azeey** [gazebosim/gz-sim#1725]
## Environment
* OS Version: Ubuntu 22.04 
* Source or binary build? binary, Garden
* If this is a GUI or sensor rendering bug, describe your GPU and rendering system. Otherwise delete this section. 
    - Rendering plugin: [ogre2]. 
      - [ ] GUI rendering error. 
    - EGL headless mode:
      - [ ] Running in EGL headless mode 
    - Generally, mention all circumstances that might affect rendering capabilities: 
      - [ ] running on a dual GPU machine (integrated GPU + discrete GPU)
      - [ ] running on a multi-GPU machine (it has multiple discrete GPUs)
      - [x] running on real hardware
      - [x] running in virtual machine
      - [x] running in Docker/Singularity
      - [ ] running remotely (e.g. via SSH)
      - [ ] running in a cloud
      - [ ] using VirtualGL, XVFB, Xdummy, XVNC or other indirect rendering utilities
      - [ ] GPU is concurrently used for other tasks
        - [ ] desktop acceleration
        - [ ] video decoding (i.e. a playing Youtube video)
        - [ ] video encoding
        - [ ] CUDA/ROCm computations (Tensorflow, Torch, Caffe running)
        - [ ] multiple simulators running at the same time
      - [ ] other...
    - Rendering system info:
      - On Linux, provide the outputs of the following commands:
          ```bash
            direct rendering: Yes
            OpenGL vendor string: NVIDIA Corporation
            OpenGL renderer string: NVIDIA GeForce GTX 780 Ti/PCIe/SSE2
            OpenGL core profile version string: 4.6.0 NVIDIA 470.141.03
            OpenGL core profile shading language version string: 4.60 NVIDIA
            OpenGL core profile context flags: (none)
            OpenGL core profile profile mask: core profile
            OpenGL version string: 4.6.0 NVIDIA 470.141.03
            OpenGL shading language version string: 4.60 NVIDIA
            OpenGL context flags: (none)
            OpenGL profile mask: (none)
            OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 470.141.03
            OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
          ```
    - [x] Please, attach the ogre.log or ogre2.log file from  `~/.ignition/rendering` 
    
<details>
  
```
16:58:44: Creating resource group General
16:58:44: Creating resource group Internal
16:58:44: Creating resource group Autodetect
16:58:44: SceneManagerFactory for type 'DefaultSceneManager' registered.
16:58:44: Registering ResourceManager for type Material
16:58:44: Registering ResourceManager for type Mesh
16:58:44: Registering ResourceManager for type Mesh2
16:58:44: Registering ResourceManager for type OldSkeleton
16:58:44: MovableObjectFactory for type 'ParticleSystem' registered.
16:58:44: ArchiveFactory for archive type FileSystem registered.
16:58:44: ArchiveFactory for archive type Zip registered.
16:58:44: ArchiveFactory for archive type EmbeddedZip registered.
16:58:44: DDS codec registering
16:58:44: FreeImage version: 3.18.0
16:58:44: This program uses FreeImage, a free, open source image library supporting all common bitmap formats. See http://freeimage.sourceforge.net for details
16:58:44: Supported formats: bmp,ico,jpg,jif,jpeg,jpe,jng,koa,iff,lbm,mng,pbm,pbm,pcd,pcx,pgm,pgm,png,ppm,ppm,ras,tga,targa,tif,tiff,wap,wbmp,wbm,psd,psb,cut,xbm,xpm,gif,hdr,g3,sgi,rgb,rgba,bw,exr,j2k,j2c,jp2,pfm,pct,pict,pic,3fr,arw,bay,bmq,cap,cine,cr2,crw,cs1,dc2,dcr,drf,dsc,dng,erf,fff,ia,iiq,k25,kc2,kdc,mdc,mef,mos,mrw,nef,nrw,orf,pef,ptx,pxn,qtk,raf,raw,rdc,rw2,rwl,rwz,sr2,srf,srw,sti,x3f,webp,jxr,wdp,hdp
16:58:44: ETC codec registering
16:58:44: OITD codec registering
16:58:44: Registering ResourceManager for type HighLevelGpuProgram
16:58:44: MovableObjectFactory for type 'Decal' registered.
16:58:44: MovableObjectFactory for type 'InternalCubemapProbe' registered.
16:58:44: MovableObjectFactory for type 'Entity' registered.
16:58:44: MovableObjectFactory for type 'Item' registered.
16:58:44: MovableObjectFactory for type 'Light' registered.
16:58:44: MovableObjectFactory for type 'Rectangle2Dv2' registered.
16:58:44: MovableObjectFactory for type 'BillboardSet' registered.
16:58:44: MovableObjectFactory for type 'ManualObject2' registered.
16:58:44: MovableObjectFactory for type 'BillboardChain' registered.
16:58:44: MovableObjectFactory for type 'RibbonTrail' registered.
16:58:44: MovableObjectFactory for type 'WireAabb' registered.
16:58:44: *-*-* OGRE Initialising
16:58:44: *-*-* Version 2.3.1 (Daedalus)
16:58:44: OverlayElementFactory for type Panel registered.
16:58:44: OverlayElementFactory for type BorderPanel registered.
16:58:44: OverlayElementFactory for type TextArea registered.
16:58:44: Registering ResourceManager for type Font
16:58:44: Loading library /usr/lib/x86_64-linux-gnu/OGRE-2.3/OGRE/RenderSystem_GL3Plus.so
16:58:44: Installing plugin: GL 3+ RenderSystem
16:58:44: OpenGL 3+ Rendering Subsystem created.
16:58:44: Found Num EGL Devices: 3
16:58:44: EGL Device: EGL_NV_device_cuda EGL_EXT_device_drm EGL_EXT_device_query_name #0 /dev/dri/card0
16:58:44: Trying to init device: EGL_NV_device_cuda EGL_EXT_device_drm EGL_EXT_device_query_name #0 /dev/dri/card0...
16:58:44: Created GL 4.5 context for device EGL_NV_device_cuda EGL_EXT_device_drm EGL_EXT_device_query_name #0 /dev/dri/card0
16:58:44: Destroying device: EGL_NV_device_cuda EGL_EXT_device_drm EGL_EXT_device_query_name #0 /dev/dri/card0...
16:58:44: EGL Device: EGL_EXT_device_drm EGL_EXT_device_drm_render_node #1 /dev/dri/card0
16:58:44: Trying to init device: EGL_EXT_device_drm EGL_EXT_device_drm_render_node #1 /dev/dri/card0...
16:58:44: OGRE EXCEPTION(3:RenderingAPIException): eglInitialize failed for device EGL_EXT_device_drm EGL_EXT_device_drm_render_node #1 /dev/dri/card0 in EGLSupport::getGLDisplay at ./RenderSystems/GL3Plus/src/windowing/EGL/PBuffer/OgreEglPBufferSupport.cpp (line 320)
16:58:44: OGRE EXCEPTION(3:RenderingAPIException): eglInitialize failed for device EGL_EXT_device_drm EGL_EXT_device_drm_render_node #1 /dev/dri/card0 in EGLSupport::getGLDisplay at ./RenderSystems/GL3Plus/src/windowing/EGL/PBuffer/OgreEglPBufferSupport.cpp (line 320)
16:58:44: Destroying device: EGL_EXT_device_drm EGL_EXT_device_drm_render_node #1 /dev/dri/card0...
16:58:44: EGL Device: EGL_MESA_device_software EGL_EXT_device_drm_render_node #2
16:58:44: Trying to init device: EGL_MESA_device_software EGL_EXT_device_drm_render_node #2...
16:58:44: Created GL 4.5 context for device EGL_MESA_device_software EGL_EXT_device_drm_render_node #2
16:58:44: Destroying device: EGL_MESA_device_software EGL_EXT_device_drm_render_node #2...
16:58:44: Plugin successfully installed
16:58:44: Loading library /usr/lib/x86_64-linux-gnu/OGRE-2.3/OGRE/Plugin_ParticleFX.so
16:58:44: Installing plugin: ParticleFX
16:58:44: Particle Emitter Type 'Point' registered
16:58:44: Particle Emitter Type 'Box' registered
16:58:44: Particle Emitter Type 'Ellipsoid' registered
16:58:44: Particle Emitter Type 'Cylinder' registered
16:58:44: Particle Emitter Type 'Ring' registered
16:58:44: Particle Emitter Type 'HollowEllipsoid' registered
16:58:44: Particle Affector Type 'LinearForce' registered
16:58:44: Particle Affector Type 'ColourFader' registered
16:58:44: Particle Affector Type 'ColourFader2' registered
16:58:44: Particle Affector Type 'ColourImage' registered
16:58:44: Particle Affector Type 'ColourInterpolator' registered
16:58:44: Particle Affector Type 'Scaler' registered
16:58:44: Particle Affector Type 'Rotator' registered
16:58:44: Particle Affector Type 'DirectionRandomiser' registered
16:58:44: Particle Affector Type 'DeflectorPlane' registered
16:58:44: Plugin successfully installed
16:58:44: CPU Identifier & Features
16:58:44: -------------------------
16:58:44:  *   CPU ID: GenuineIntel: Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
16:58:44:  *   Logical cores: 4
16:58:44:  *      SSE: yes
16:58:44:  *     SSE2: yes
16:58:44:  *     SSE3: yes
16:58:44:  *      MMX: yes
16:58:44:  *   MMXEXT: yes
16:58:44:  *    3DNOW: no
16:58:44:  * 3DNOWEXT: no
16:58:44:  *     CMOV: yes
16:58:44:  *      TSC: yes
16:58:44:  *      FPU: yes
16:58:44:  *      PRO: yes
16:58:44:  *       HT: no
16:58:44: -------------------------
16:58:44: ******************************
*** Starting GLX Subsystem ***
******************************
16:58:44: GL3PlusRenderSystem::_createRenderWindow "OgreWindow(0)_0", 1x1 windowed  miscParams: FSAA=0 border=none contentScalingFactor=1.000000 currentGLContext=true externalGLControl=true gamma=Yes parentWindowHandle=33554446 stereoMode=Frame Sequential
16:58:44: GLXWindow::create used FBConfigID = 261
16:58:44: GL Version = 4.6.0.0
16:58:44: GL_VERSION = 4.6.0 NVIDIA 470.141.03
16:58:44: GL_VENDOR = NVIDIA Corporation
16:58:44: GL_RENDERER = NVIDIA GeForce GTX 780 Ti/PCIe/SSE2
16:58:44: GL_EXTENSIONS =
16:58:44: GL_AMD_multi_draw_indirect
16:58:44: GL_AMD_seamless_cubemap_per_texture
16:58:44: GL_ARB_arrays_of_arrays
16:58:44: GL_ARB_base_instance
16:58:44: GL_ARB_bindless_texture
16:58:44: GL_ARB_blend_func_extended
16:58:44: GL_ARB_buffer_storage
16:58:44: GL_ARB_clear_buffer_object
16:58:44: GL_ARB_clear_texture
16:58:44: GL_ARB_clip_control
16:58:44: GL_ARB_color_buffer_float
16:58:44: GL_ARB_compatibility
16:58:44: GL_ARB_compressed_texture_pixel_storage
16:58:44: GL_ARB_conservative_depth
16:58:44: GL_ARB_compute_shader
16:58:44: GL_ARB_compute_variable_group_size
16:58:44: GL_ARB_conditional_render_inverted
16:58:44: GL_ARB_copy_buffer
16:58:44: GL_ARB_copy_image
16:58:44: GL_ARB_cull_distance
16:58:44: GL_ARB_debug_output
16:58:44: GL_ARB_depth_buffer_float
16:58:44: GL_ARB_depth_clamp
16:58:44: GL_ARB_depth_texture
16:58:44: GL_ARB_derivative_control
16:58:44: GL_ARB_direct_state_access
16:58:44: GL_ARB_draw_buffers
16:58:44: GL_ARB_draw_buffers_blend
16:58:44: GL_ARB_draw_indirect
16:58:44: GL_ARB_draw_elements_base_vertex
16:58:44: GL_ARB_draw_instanced
16:58:44: GL_ARB_enhanced_layouts
16:58:44: GL_ARB_ES2_compatibility
16:58:44: GL_ARB_ES3_compatibility
16:58:44: GL_ARB_ES3_1_compatibility
16:58:44: GL_ARB_ES3_2_compatibility
16:58:44: GL_ARB_explicit_attrib_location
16:58:44: GL_ARB_explicit_uniform_location
16:58:44: GL_ARB_fragment_coord_conventions
16:58:44: GL_ARB_fragment_layer_viewport
16:58:44: GL_ARB_fragment_program
16:58:44: GL_ARB_fragment_program_shadow
16:58:44: GL_ARB_fragment_shader
16:58:44: GL_ARB_framebuffer_no_attachments
16:58:44: GL_ARB_framebuffer_object
16:58:44: GL_ARB_framebuffer_sRGB
16:58:44: GL_ARB_geometry_shader4
16:58:44: GL_ARB_get_program_binary
16:58:44: GL_ARB_get_texture_sub_image
16:58:44: GL_ARB_gl_spirv
16:58:44: GL_ARB_gpu_shader5
16:58:44: GL_ARB_gpu_shader_fp64
16:58:44: GL_ARB_gpu_shader_int64
16:58:44: GL_ARB_half_float_pixel
16:58:44: GL_ARB_half_float_vertex
16:58:44: GL_ARB_imaging
16:58:44: GL_ARB_indirect_parameters
16:58:44: GL_ARB_instanced_arrays
16:58:44: GL_ARB_internalformat_query
16:58:44: GL_ARB_internalformat_query2
16:58:44: GL_ARB_invalidate_subdata
16:58:44: GL_ARB_map_buffer_alignment
16:58:44: GL_ARB_map_buffer_range
16:58:44: GL_ARB_multi_bind
16:58:44: GL_ARB_multi_draw_indirect
16:58:44: GL_ARB_multisample
16:58:44: GL_ARB_multitexture
16:58:44: GL_ARB_occlusion_query
16:58:44: GL_ARB_occlusion_query2
16:58:44: GL_ARB_parallel_shader_compile
16:58:44: GL_ARB_pipeline_statistics_query
16:58:44: GL_ARB_pixel_buffer_object
16:58:44: GL_ARB_point_parameters
16:58:44: GL_ARB_point_sprite
16:58:44: GL_ARB_polygon_offset_clamp
16:58:44: GL_ARB_program_interface_query
16:58:44: GL_ARB_provoking_vertex
16:58:44: GL_ARB_query_buffer_object
16:58:44: GL_ARB_robust_buffer_access_behavior
16:58:44: GL_ARB_robustness
16:58:44: GL_ARB_sample_shading
16:58:44: GL_ARB_sampler_objects
16:58:44: GL_ARB_seamless_cube_map
16:58:44: GL_ARB_seamless_cubemap_per_texture
16:58:44: GL_ARB_separate_shader_objects
16:58:44: GL_ARB_shader_atomic_counter_ops
16:58:44: GL_ARB_shader_atomic_counters
16:58:44: GL_ARB_shader_ballot
16:58:44: GL_ARB_shader_bit_encoding
16:58:44: GL_ARB_shader_clock
16:58:44: GL_ARB_shader_draw_parameters
16:58:44: GL_ARB_shader_group_vote
16:58:44: GL_ARB_shader_image_load_store
16:58:44: GL_ARB_shader_image_size
16:58:44: GL_ARB_shader_objects
16:58:44: GL_ARB_shader_precision
16:58:44: GL_ARB_shader_storage_buffer_object
16:58:44: GL_ARB_shader_subroutine
16:58:44: GL_ARB_shader_texture_image_samples
16:58:44: GL_ARB_shader_texture_lod
16:58:44: GL_ARB_shading_language_100
16:58:44: GL_ARB_shading_language_420pack
16:58:44: GL_ARB_shading_language_include
16:58:44: GL_ARB_shading_language_packing
16:58:44: GL_ARB_shadow
16:58:44: GL_ARB_sparse_buffer
16:58:44: GL_ARB_sparse_texture
16:58:44: GL_ARB_spirv_extensions
16:58:44: GL_ARB_stencil_texturing
16:58:44: GL_ARB_sync
16:58:44: GL_ARB_tessellation_shader
16:58:44: GL_ARB_texture_barrier
16:58:44: GL_ARB_texture_border_clamp
16:58:44: GL_ARB_texture_buffer_object
16:58:44: GL_ARB_texture_buffer_object_rgb32
16:58:44: GL_ARB_texture_buffer_range
16:58:44: GL_ARB_texture_compression
16:58:44: GL_ARB_texture_compression_bptc
16:58:44: GL_ARB_texture_compression_rgtc
16:58:44: GL_ARB_texture_cube_map
16:58:44: GL_ARB_texture_cube_map_array
16:58:44: GL_ARB_texture_env_add
16:58:44: GL_ARB_texture_env_combine
16:58:44: GL_ARB_texture_env_crossbar
16:58:44: GL_ARB_texture_env_dot3
16:58:44: GL_ARB_texture_filter_anisotropic
16:58:44: GL_ARB_texture_float
16:58:44: GL_ARB_texture_gather
16:58:44: GL_ARB_texture_mirror_clamp_to_edge
16:58:44: GL_ARB_texture_mirrored_repeat
16:58:44: GL_ARB_texture_multisample
16:58:44: GL_ARB_texture_non_power_of_two
16:58:44: GL_ARB_texture_query_levels
16:58:44: GL_ARB_texture_query_lod
16:58:44: GL_ARB_texture_rectangle
16:58:44: GL_ARB_texture_rg
16:58:44: GL_ARB_texture_rgb10_a2ui
16:58:44: GL_ARB_texture_stencil8
16:58:44: GL_ARB_texture_storage
16:58:44: GL_ARB_texture_storage_multisample
16:58:44: GL_ARB_texture_swizzle
16:58:44: GL_ARB_texture_view
16:58:44: GL_ARB_timer_query
16:58:44: GL_ARB_transform_feedback2
16:58:44: GL_ARB_transform_feedback3
16:58:44: GL_ARB_transform_feedback_instanced
16:58:44: GL_ARB_transform_feedback_overflow_query
16:58:44: GL_ARB_transpose_matrix
16:58:44: GL_ARB_uniform_buffer_object
16:58:44: GL_ARB_vertex_array_bgra
16:58:44: GL_ARB_vertex_array_object
16:58:44: GL_ARB_vertex_attrib_64bit
16:58:44: GL_ARB_vertex_attrib_binding
16:58:44: GL_ARB_vertex_buffer_object
16:58:44: GL_ARB_vertex_program
16:58:44: GL_ARB_vertex_shader
16:58:44: GL_ARB_vertex_type_10f_11f_11f_rev
16:58:44: GL_ARB_vertex_type_2_10_10_10_rev
16:58:44: GL_ARB_viewport_array
16:58:44: GL_ARB_window_pos
16:58:44: GL_ATI_draw_buffers
16:58:44: GL_ATI_texture_float
16:58:44: GL_ATI_texture_mirror_once
16:58:44: GL_S3_s3tc
16:58:44: GL_EXT_texture_env_add
16:58:44: GL_EXT_abgr
16:58:44: GL_EXT_bgra
16:58:44: GL_EXT_bindable_uniform
16:58:44: GL_EXT_blend_color
16:58:44: GL_EXT_blend_equation_separate
16:58:44: GL_EXT_blend_func_separate
16:58:44: GL_EXT_blend_minmax
16:58:44: GL_EXT_blend_subtract
16:58:44: GL_EXT_compiled_vertex_array
16:58:44: GL_EXT_Cg_shader
16:58:44: GL_EXT_depth_bounds_test
16:58:44: GL_EXT_direct_state_access
16:58:44: GL_EXT_draw_buffers2
16:58:44: GL_EXT_draw_instanced
16:58:44: GL_EXT_draw_range_elements
16:58:44: GL_EXT_fog_coord
16:58:44: GL_EXT_framebuffer_blit
16:58:44: GL_EXT_framebuffer_multisample
16:58:44: GL_EXTX_framebuffer_mixed_formats
16:58:44: GL_EXT_framebuffer_multisample_blit_scaled
16:58:44: GL_EXT_framebuffer_object
16:58:44: GL_EXT_framebuffer_sRGB
16:58:44: GL_EXT_geometry_shader4
16:58:44: GL_EXT_gpu_program_parameters
16:58:44: GL_EXT_gpu_shader4
16:58:44: GL_EXT_multi_draw_arrays
16:58:44: GL_EXT_multiview_texture_multisample
16:58:44: GL_EXT_multiview_timer_query
16:58:44: GL_EXT_packed_depth_stencil
16:58:44: GL_EXT_packed_float
16:58:44: GL_EXT_packed_pixels
16:58:44: GL_EXT_pixel_buffer_object
16:58:44: GL_EXT_point_parameters
16:58:44: GL_EXT_polygon_offset_clamp
16:58:44: GL_EXT_provoking_vertex
16:58:44: GL_EXT_rescale_normal
16:58:44: GL_EXT_secondary_color
16:58:44: GL_EXT_separate_shader_objects
16:58:44: GL_EXT_separate_specular_color
16:58:44: GL_EXT_shader_image_load_store
16:58:44: GL_EXT_shader_integer_mix
16:58:44: GL_EXT_shadow_funcs
16:58:44: GL_EXT_stencil_two_side
16:58:44: GL_EXT_stencil_wrap
16:58:44: GL_EXT_texture3D
16:58:44: GL_EXT_texture_array
16:58:44: GL_EXT_texture_buffer_object
16:58:44: GL_EXT_texture_compression_dxt1
16:58:44: GL_EXT_texture_compression_latc
16:58:44: GL_EXT_texture_compression_rgtc
16:58:44: GL_EXT_texture_compression_s3tc
16:58:44: GL_EXT_texture_cube_map
16:58:44: GL_EXT_texture_edge_clamp
16:58:44: GL_EXT_texture_env_combine
16:58:44: GL_EXT_texture_env_dot3
16:58:44: GL_EXT_texture_filter_anisotropic
16:58:44: GL_EXT_texture_integer
16:58:44: GL_EXT_texture_lod
16:58:44: GL_EXT_texture_lod_bias
16:58:44: GL_EXT_texture_mirror_clamp
16:58:44: GL_EXT_texture_object
16:58:44: GL_EXT_texture_shadow_lod
16:58:44: GL_EXT_texture_shared_exponent
16:58:44: GL_EXT_texture_sRGB
16:58:44: GL_EXT_texture_sRGB_R8
16:58:44: GL_EXT_texture_sRGB_decode
16:58:44: GL_EXT_texture_storage
16:58:44: GL_EXT_texture_swizzle
16:58:44: GL_EXT_timer_query
16:58:44: GL_EXT_transform_feedback2
16:58:44: GL_EXT_vertex_array
16:58:44: GL_EXT_vertex_array_bgra
16:58:44: GL_EXT_vertex_attrib_64bit
16:58:44: GL_EXT_window_rectangles
16:58:44: GL_EXT_x11_sync_object
16:58:44: GL_EXT_import_sync_object
16:58:44: GL_NV_robustness_video_memory_purge
16:58:44: GL_IBM_rasterpos_clip
16:58:44: GL_IBM_texture_mirrored_repeat
16:58:44: GL_KHR_context_flush_control
16:58:44: GL_KHR_debug
16:58:44: GL_EXT_memory_object
16:58:44: GL_EXT_memory_object_fd
16:58:44: GL_KHR_parallel_shader_compile
16:58:44: GL_KHR_no_error
16:58:44: GL_KHR_robust_buffer_access_behavior
16:58:44: GL_KHR_robustness
16:58:44: GL_EXT_semaphore
16:58:44: GL_EXT_semaphore_fd
16:58:44: GL_NV_timeline_semaphore
16:58:44: GL_KHR_shader_subgroup
16:58:44: GL_KTX_buffer_region
16:58:44: GL_NV_alpha_to_coverage_dither_control
16:58:44: GL_NV_bindless_multi_draw_indirect
16:58:44: GL_NV_bindless_multi_draw_indirect_count
16:58:44: GL_NV_bindless_texture
16:58:44: GL_NV_blend_equation_advanced
16:58:44: GL_NV_blend_square
16:58:44: GL_NV_command_list
16:58:44: GL_NV_compute_program5
16:58:44: GL_NV_conditional_render
16:58:44: GL_NV_copy_depth_to_color
16:58:44: GL_NV_copy_image
16:58:44: GL_NV_depth_buffer_float
16:58:44: GL_NV_depth_clamp
16:58:44: GL_NV_draw_texture
16:58:44: GL_NV_draw_vulkan_image
16:58:44: GL_NV_ES1_1_compatibility
16:58:44: GL_NV_ES3_1_compatibility
16:58:44: GL_NV_explicit_multisample
16:58:44: GL_NV_feature_query
16:58:44: GL_NV_fence
16:58:44: GL_NV_float_buffer
16:58:44: GL_NV_fog_distance
16:58:44: GL_NV_fragment_program
16:58:44: GL_NV_fragment_program_option
16:58:44: GL_NV_fragment_program2
16:58:44: GL_NV_framebuffer_multisample_coverage
16:58:44: GL_NV_geometry_shader4
16:58:44: GL_NV_gpu_program4
16:58:44: GL_NV_internalformat_sample_query
16:58:44: GL_NV_gpu_program4_1
16:58:44: GL_NV_gpu_program5
16:58:44: GL_NV_gpu_program5_mem_extended
16:58:44: GL_NV_gpu_program_fp64
16:58:44: GL_NV_gpu_shader5
16:58:44: GL_NV_half_float
16:58:44: GL_NV_light_max_exponent
16:58:44: GL_NV_multisample_coverage
16:58:44: GL_NV_multisample_filter_hint
16:58:44: GL_NV_occlusion_query
16:58:44: GL_NV_packed_depth_stencil
16:58:44: GL_NV_parameter_buffer_object
16:58:44: GL_NV_parameter_buffer_object2
16:58:44: GL_NV_path_rendering
16:58:44: GL_NV_pixel_data_range
16:58:44: GL_NV_point_sprite
16:58:44: GL_NV_primitive_restart
16:58:44: GL_NV_query_resource
16:58:44: GL_NV_query_resource_tag
16:58:44: GL_NV_register_combiners
16:58:44: GL_NV_register_combiners2
16:58:44: GL_NV_shader_atomic_counters
16:58:44: GL_NV_shader_atomic_float
16:58:44: GL_NV_shader_atomic_int64
16:58:44: GL_NV_shader_buffer_load
16:58:44: GL_NV_shader_storage_buffer_object
16:58:44: GL_NV_shader_subgroup_partitioned
16:58:44: GL_NV_texgen_reflection
16:58:44: GL_NV_texture_barrier
16:58:44: GL_NV_texture_compression_vtc
16:58:44: GL_NV_texture_env_combine4
16:58:44: GL_NV_texture_multisample
16:58:44: GL_NV_texture_rectangle
16:58:44: GL_NV_texture_rectangle_compressed
16:58:44: GL_NV_texture_shader
16:58:44: GL_NV_texture_shader2
16:58:44: GL_NV_texture_shader3
16:58:44: GL_NV_transform_feedback
16:58:44: GL_NV_transform_feedback2
16:58:44: GL_NV_uniform_buffer_unified_memory
16:58:44: GL_NV_vdpau_interop
16:58:44: GL_NV_vdpau_interop2
16:58:44: GL_NV_vertex_array_range
16:58:44: GL_NV_vertex_array_range2
16:58:44: GL_NV_vertex_attrib_integer_64bit
16:58:44: GL_NV_vertex_buffer_unified_memory
16:58:44: GL_NV_vertex_program
16:58:44: GL_NV_vertex_program1_1
16:58:44: GL_NV_vertex_program2
16:58:44: GL_NV_vertex_program2_option
16:58:44: GL_NV_vertex_program3
16:58:44: GL_NVX_conditional_render
16:58:44: GL_NV_gpu_multicast
16:58:44: GL_NVX_progress_fence
16:58:44: GL_NVX_gpu_memory_info
16:58:44: GL_NVX_nvenc_interop
16:58:44: GL_NV_shader_thread_group
16:58:44: GL_NV_shader_thread_shuffle
16:58:44: GL_KHR_blend_equation_advanced
16:58:44: GL_OVR_multiview
16:58:44: GL_OVR_multiview2
16:58:44: GL_SGIS_generate_mipmap
16:58:44: GL_SGIS_texture_lod
16:58:44: GL_SGIX_depth_texture
16:58:44: GL_SGIX_shadow
16:58:44: GL_SUN_slice_accum
16:58:44: **************************************
16:58:44: ***   OpenGL 3+ Renderer Started   ***
16:58:44: **************************************
16:58:44: Registering ResourceManager for type GpuProgram
16:58:44: RenderSystem capabilities
16:58:44: -------------------------
16:58:44: RenderSystem Name: OpenGL 3+ Rendering Subsystem
16:58:44: GPU Vendor: nvidia
16:58:44: Device Name: NVIDIA GeForce GTX 780 Ti/PCIe/SSE2
16:58:44: Driver Version: 4.6.0.0
16:58:44:  * Fixed function pipeline: no
16:58:44:  * Hardware generation of mipmaps: yes
16:58:44:  * Texture blending: yes
16:58:44:  * Anisotropic texture filtering: yes
16:58:44:  * Dot product texture operation: yes
16:58:44:  * Cube mapping: yes
16:58:44:  * Hardware stencil buffer: yes
16:58:44:    - Stencil depth: 8
16:58:44:    - Two sided stencil support: yes
16:58:44:    - Wrap stencil values: yes
16:58:44:  * Hardware vertex / index buffers: yes
16:58:44:  * 32-bit index buffers: yes
16:58:44:  * Vertex programs: yes
16:58:44:  * Number of floating-point constants for vertex programs: 4096
16:58:44:  * Number of integer constants for vertex programs: 4096
16:58:44:  * Number of boolean constants for vertex programs: 4096
16:58:44:  * Fragment programs: yes
16:58:44:  * Number of floating-point constants for fragment programs: 4096
16:58:44:  * Number of integer constants for fragment programs: 4096
16:58:44:  * Number of boolean constants for fragment programs: 4096
16:58:44:  * Geometry programs: yes
16:58:44:  * Number of floating-point constants for geometry programs: 2048
16:58:44:  * Number of integer constants for geometry programs: 2048
16:58:44:  * Number of boolean constants for geometry programs: 2048
16:58:44:  * Tessellation Hull programs: yes
16:58:44:  * Number of floating-point constants for tessellation hull programs: 2048
16:58:44:  * Number of integer constants for tessellation hull programs: 2048
16:58:44:  * Number of boolean constants for tessellation hull programs: 2048
16:58:44:  * Tessellation Domain programs: yes
16:58:44:  * Number of floating-point constants for tessellation domain programs: 2048
16:58:44:  * Number of integer constants for tessellation domain programs: 2048
16:58:44:  * Number of boolean constants for tessellation domain programs: 2048
16:58:44:  * Compute programs: yes
16:58:44:  * Number of floating-point constants for compute programs: 2048
16:58:44:  * Number of integer constants for compute programs: 2048
16:58:44:  * Number of boolean constants for compute programs: 2048
16:58:44:  * Supported Shader Profiles: glsl glsl130 glsl140 glsl150 glsl330 glsl400 glsl410 glsl420 glsl430 glsl440
16:58:44:  * Texture Compression: yes
16:58:44:    - DXT: yes
16:58:44:    - VTC: yes
16:58:44:    - PVRTC: no
16:58:44:    - ATC: no
16:58:44:    - ETC1: no
16:58:44:    - ETC2: yes
16:58:44:    - BC4/BC5: yes
16:58:44:    - BC6H/BC7: yes
16:58:44:    - ASTC: no
16:58:44:  * Hardware Occlusion Query: yes
16:58:44:  * User clip planes: yes
16:58:44:  * VET_UBYTE4 vertex element type: yes
16:58:44:  * Infinite far plane projection: yes
16:58:44:  * Hardware render-to-texture: yes
16:58:44:  * Floating point textures: yes
16:58:44:  * Non-power-of-two textures: yes
16:58:44:  * 1d textures: yes
16:58:44:  * Volume textures: yes
16:58:44:  * Max Texture resolution (2D) 16384
16:58:44:  * Max Texture resolution (3D) 2048
16:58:44:  * Max Texture resolution (Cubemaps) 16384
16:58:44:  * Multiple Render Targets: 8
16:58:44:    - With different bit depths: yes
16:58:44:  * Point Sprites: yes
16:58:44:  * Extended point parameters: yes
16:58:44:  * Max Point Size: 189.875
16:58:44:  * Vertex texture fetch: yes
16:58:44:  * Number of world matrices: 0
16:58:44:  * Number of texture units: 16
16:58:44:  * Stencil buffer depth: 8
16:58:44:  * Number of vertex blend matrices: 0
16:58:44:    - Max vertex textures: 32
16:58:44:    - Vertex textures shared: yes
16:58:44:  * Render to Vertex Buffer : yes
16:58:44:  * Hardware Atomic Counters: yes
16:58:44:  * Compute max threads per threadgroup per axis: 1024, 1024, 64
16:58:44:  * Compute max threads per threadgroup total: 1024
16:58:44:  * GL 1.5 without VBO workaround: no
16:58:44:  * Frame Buffer objects: yes
16:58:44:  * Frame Buffer objects (ARB extension): no
16:58:44:  * Frame Buffer objects (ATI extension): no
16:58:44:  * PBuffer support: no
16:58:44:  * GL 1.5 without HW-occlusion workaround: no
16:58:44:  * Vertex Array Objects: yes
16:58:44:  * Separate shader objects: no
16:58:44:  * Using Reverse Z: yes
16:58:44: DefaultWorkQueue('Root') initialising on thread main.
16:58:44: Particle Renderer Type 'billboard' registered
16:58:44: Added resource location '/usr/share/gz/gz-rendering7/ogre2/media/2.0/scripts/Compositors' of type 'FileSystem' to resource group 'General'
16:58:44: Added resource location '/usr/share/gz/gz-rendering7/ogre2/media/2.0/scripts/materials/Common' of type 'FileSystem' to resource group 'General'
16:58:44: Added resource location '/usr/share/gz/gz-rendering7/ogre2/media/2.0/scripts/materials/Common/GLSL' of type 'FileSystem' to resource group 'General'
16:58:44: Added resource location '/usr/share/gz/gz-rendering7/ogre2/media/2.0/scripts/materials/Terra' of type 'FileSystem' to resource group 'General'
16:58:44: Added resource location '/usr/share/gz/gz-rendering7/ogre2/media/2.0/scripts/materials/Terra/GLSL' of type 'FileSystem' to resource group 'General'
16:58:44: HLMS Library path '/usr/share/gz/gz-rendering7/ogre2/media/Hlms/Gz' has no piece files. Are you sure you provided the right path with read access?
16:58:44: HLMS Library path '/usr/share/gz/gz-rendering7/ogre2/media/Hlms/Gz' has no piece files. Are you sure you provided the right path with read access?
16:58:44: Added resource location '/usr/share/gz/gz-rendering7/ogre2/media' of type 'FileSystem' to resource group 'General'
16:58:44: Added resource location '/usr/share/gz/gz-rendering7/ogre2/media/materials/programs' of type 'FileSystem' to resource group 'General'
16:58:44: Added resource location '/usr/share/gz/gz-rendering7/ogre2/media/materials/programs/GLSL' of type 'FileSystem' to resource group 'General'
16:58:44: Added resource location '/usr/share/gz/gz-rendering7/ogre2/media/materials/programs/Metal' of type 'FileSystem' to resource group 'General'
16:58:44: Added resource location '/usr/share/gz/gz-rendering7/ogre2/media/materials/scripts' of type 'FileSystem' to resource group 'General'
16:58:44: Added resource location '/usr/share/gz/gz-rendering7/ogre2/media/materials/textures' of type 'FileSystem' to resource group 'General'
16:58:44: Parsing scripts for resource group Autodetect
16:58:44: Finished parsing scripts for resource group Autodetect
16:58:44: Creating resources for group Autodetect
16:58:44: All done
16:58:44: Parsing scripts for resource group General
16:58:44: Parsing script Quad.program
16:58:44: Parsing script picker.program
16:58:44: Parsing script EsmGaussianBlurLogFilter.material
16:58:44: Parsing script DPSM.material
16:58:44: Parsing script Copyback.material
16:58:44: Parsing script DepthUtils.material
16:58:44: Parsing script GpuNormalMapper.material
16:58:44: Parsing script skybox.material
16:58:44: Parsing script selection_buffer.material
16:58:44: Parsing script gpu_rays.material
16:58:44: Parsing script point_cloud_point.material
16:58:44: Parsing script depth_camera.material
16:58:44: Parsing script gaussian_noise.material
16:58:44: Parsing script thermal.material
16:58:44: Parsing script picker.material
16:58:44: Parsing script TerraShadowGenerator.compositor
16:58:44: Parsing script GpuNormalMapper.compositor
16:58:44: Parsing script GpuRays.compositor
16:58:44: Parsing script Mipmaps.material.json
16:58:44: Parsing script EsmGaussianBlurLogFilter.material.json
16:58:44: Parsing script TerraShadowGenerator.material.json
16:58:44: Finished parsing scripts for resource group General
16:58:44: Creating resources for group General
16:58:44: All done
16:58:44: Parsing scripts for resource group Internal
16:58:44: Finished parsing scripts for resource group Internal
16:58:44: Creating resources for group Internal
16:58:44: All done
16:58:44: Added resource location '/usr/share/gz/gz-rendering7/media/materials/textures/' of type 'FileSystem' to resource group 'General'
16:58:45: Can't assign material [Default] because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:45: Can't assign material scene::Material(65503) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:45: Can't assign material scene::Material(65497) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:45: Can't assign material scene::Material(65491) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:45: Can't assign material scene::Material(65485) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:45: Can't assign material scene::Material(65478) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:45: Can't assign material scene::Material(65485) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:45: Can't assign material scene::Material(65466) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:45: OGRE EXCEPTION(3:RenderingAPIException): Fixed Function pipeline is no longer allowed nor supported. The material scene::Material(65518) must use shaders in HlmsLowLevel::calculateHashFor at ./OgreMain/src/OgreHlmsLowLevel.cpp (line 160)
16:58:45: OGRE EXCEPTION(3:RenderingAPIException): Fixed Function pipeline is no longer allowed nor supported. The material scene::Material(65518) must use shaders in HlmsLowLevel::calculateHashFor at ./OgreMain/src/OgreHlmsLowLevel.cpp (line 160)
16:58:45: Couldn't apply datablock '[Hash 0x973c97a7]' to this renderable. Using default one. Check previous log messages to see if there's more information.
16:58:45: OGRE EXCEPTION(3:RenderingAPIException): Fixed Function pipeline is no longer allowed nor supported. The material scene::Material(65518) must use shaders in HlmsLowLevel::calculateHashFor at ./OgreMain/src/OgreHlmsLowLevel.cpp (line 160)
16:58:45: OGRE EXCEPTION(3:RenderingAPIException): Fixed Function pipeline is no longer allowed nor supported. The material scene::Material(65518) must use shaders in HlmsLowLevel::calculateHashFor at ./OgreMain/src/OgreHlmsLowLevel.cpp (line 160)
16:58:45: Couldn't apply datablock '[Hash 0x973c97a7]' to this renderable. Using default one. Check previous log messages to see if there's more information.
16:58:45: OGRE EXCEPTION(3:RenderingAPIException): Fixed Function pipeline is no longer allowed nor supported. The material Default/TransGreen must use shaders in HlmsLowLevel::calculateHashFor at ./OgreMain/src/OgreHlmsLowLevel.cpp (line 160)
16:58:45: OGRE EXCEPTION(3:RenderingAPIException): Fixed Function pipeline is no longer allowed nor supported. The material Default/TransGreen must use shaders in HlmsLowLevel::calculateHashFor at ./OgreMain/src/OgreHlmsLowLevel.cpp (line 160)
16:58:45: Couldn't apply datablock '[Hash 0x4dac4408]' to this renderable. Using default one. Check previous log messages to see if there's more information.
16:58:45: WARNING: Deleting mapped buffer without having it unmapped. This is often sign of a resource leak or a bad pattern. Umapping the buffer for you...
16:58:45: WARNING: Deleting mapped buffer without having it unmapped. This is often sign of a resource leak or a bad pattern. Umapping the buffer for you...
16:58:45: WARNING: Deleting mapped buffer without having it unmapped. This is often sign of a resource leak or a bad pattern. Umapping the buffer for you...
16:58:45: WARNING: Deleting mapped buffer without having it unmapped. This is often sign of a resource leak or a bad pattern. Umapping the buffer for you...
16:58:47: Can't assign material [Default] because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:47: OGRE EXCEPTION(3:RenderingAPIException): Fixed Function pipeline is no longer allowed nor supported. The material highlight_material must use shaders in HlmsLowLevel::calculateHashFor at ./OgreMain/src/OgreHlmsLowLevel.cpp (line 160)
16:58:47: OGRE EXCEPTION(3:RenderingAPIException): Fixed Function pipeline is no longer allowed nor supported. The material highlight_material must use shaders in HlmsLowLevel::calculateHashFor at ./OgreMain/src/OgreHlmsLowLevel.cpp (line 160)
16:58:47: Couldn't apply datablock '[Hash 0xae9cf106]' to this renderable. Using default one. Check previous log messages to see if there's more information.
16:58:47: OGRE EXCEPTION(3:RenderingAPIException): Fixed Function pipeline is no longer allowed nor supported. The material highlight_material must use shaders in HlmsLowLevel::calculateHashFor at ./OgreMain/src/OgreHlmsLowLevel.cpp (line 160)
16:58:47: OGRE EXCEPTION(3:RenderingAPIException): Fixed Function pipeline is no longer allowed nor supported. The material highlight_material must use shaders in HlmsLowLevel::calculateHashFor at ./OgreMain/src/OgreHlmsLowLevel.cpp (line 160)
16:58:47: Couldn't apply datablock '[Hash 0xae9cf106]' to this renderable. Using default one. Check previous log messages to see if there's more information.
16:58:47: WARNING: Deleting mapped buffer without having it unmapped. This is often sign of a resource leak or a bad pattern. Umapping the buffer for you...
16:58:47: WARNING: Deleting mapped buffer without having it unmapped. This is often sign of a resource leak or a bad pattern. Umapping the buffer for you...
16:58:47: WARNING: Deleting mapped buffer without having it unmapped. This is often sign of a resource leak or a bad pattern. Umapping the buffer for you...
16:58:48: Can't assign material scene::Material(65491) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65443) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65491) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65443) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65491) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65443) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65485) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65491) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65491) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65491) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65491) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65497) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65491) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65497) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65491) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65497) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65491) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65491) because this Material does not exist. Have you forgotten to define it in a .material script?
16:58:48: Can't assign material scene::Material(65491) because this Material does not exist. Have you forgotten to define it in a .material script?


```

</details>

## Description
* Expected behavior: Rotate gizmo to appear when activating the rotate tool
* Actual behavior: Rotate gizmo does not appear

## Steps to reproduce

1. Run `gz sim -v3 shapes.sdf`
2. Select cube and activate rotate tool

## Output
Relevant logs:
```
[GUI] [Err] [MeshDescriptor.cc:56] Mesh manager can't find mesh named [gizmo_rotate]
[GUI] [Err] [Ogre2MeshFactory.cc:566] Cannot load null mesh [gizmo_rotate]
[GUI] [Err] [Ogre2MeshFactory.cc:125] Failed to get Ogre item for [gizmo_rotate]
[GUI] [Err] [Ogre2Visual.cc:134] Cannot attach null geometry.
[GUI] [Err] [MeshDescriptor.cc:56] Mesh manager can't find mesh named [gizmo_rotate]
[GUI] [Err] [Ogre2MeshFactory.cc:566] Cannot load null mesh [gizmo_rotate]
[GUI] [Err] [Ogre2MeshFactory.cc:125] Failed to get Ogre item for [gizmo_rotate]
[GUI] [Err] [Ogre2Visual.cc:134] Cannot attach null geometry.
[GUI] [Err] [MeshDescriptor.cc:56] Mesh manager can't find mesh named [gizmo_rotate]
[GUI] [Err] [Ogre2MeshFactory.cc:566] Cannot load null mesh [gizmo_rotate]
[GUI] [Err] [Ogre2MeshFactory.cc:125] Failed to get Ogre item for [gizmo_rotate]
[GUI] [Err] [Ogre2Visual.cc:134] Cannot attach null geometry.
[GUI] [Err] [MeshDescriptor.cc:56] Mesh manager can't find mesh named [gizmo_rotate_full]
[GUI] [Err] [Ogre2MeshFactory.cc:566] Cannot load null mesh [gizmo_rotate_full]
[GUI] [Err] [Ogre2MeshFactory.cc:125] Failed to get Ogre item for [gizmo_rotate_full]
[GUI] [Err] [Ogre2Visual.cc:134] Cannot attach null geometry.
[GUI] [Err] [MeshDescriptor.cc:56] Mesh manager can't find mesh named [gizmo_rotate_handle]
[GUI] [Err] [Ogre2MeshFactory.cc:566] Cannot load null mesh [gizmo_rotate_handle]
[GUI] [Err] [Ogre2MeshFactory.cc:125] Failed to get Ogre item for [gizmo_rotate_handle]
[GUI] [Err] [Ogre2Visual.cc:134] Cannot attach null geometry.
[GUI] [Err] [MeshDescriptor.cc:56] Mesh manager can't find mesh named [gizmo_rotate_handle]
[GUI] [Err] [Ogre2MeshFactory.cc:566] Cannot load null mesh [gizmo_rotate_handle]
[GUI] [Err] [Ogre2MeshFactory.cc:125] Failed to get Ogre item for [gizmo_rotate_handle]
[GUI] [Err] [Ogre2Visual.cc:134] Cannot attach null geometry.
[GUI] [Err] [MeshDescriptor.cc:56] Mesh manager can't find mesh named [gizmo_rotate_handle]
[GUI] [Err] [Ogre2MeshFactory.cc:566] Cannot load null mesh [gizmo_rotate_handle]
[GUI] [Err] [Ogre2MeshFactory.cc:125] Failed to get Ogre item for [gizmo_rotate_handle]
[GUI] [Err] [Ogre2Visual.cc:134] Cannot attach null geometry.
```

Might be related to https://github.com/gazebosim/gz-sim/issues/1705

**Comment by iche033** [comment]
hmm I just setup Garden on Jammy in fresh docker container but I'm not able to reproduce the issue..

![rotate_gizmo_jammy](https://user-images.githubusercontent.com/4000684/192390044-78416913-c07c-4404-9c7e-3b36ad2c236d.png)

**Comment by azeey** [comment]
@iche033 , interesting. Were you building from source or did you use binaries?

**Comment by iche033** [comment]
I built Garden from source

**Comment by ahcorde** [comment]
I can see these errors:

```bash
[GUI] [Err] [MeshDescriptor.cc:54] Mesh manager can't find mesh named [gizmo_rotate]
[GUI] [Err] [Ogre2MeshFactory.cc:566] Cannot load null mesh [gizmo_rotate]
[GUI] [Err] [Ogre2MeshFactory.cc:125] Failed to get Ogre item for [gizmo_rotate]
[GUI] [Err] [Ogre2Visual.cc:134] Cannot attach null geometry.
[GUI] [Err] [MeshDescriptor.cc:54] Mesh manager can't find mesh named [gizmo_rotate]
[GUI] [Err] [Ogre2MeshFactory.cc:566] Cannot load null mesh [gizmo_rotate]
[GUI] [Err] [Ogre2MeshFactory.cc:125] Failed to get Ogre item for [gizmo_rotate]
[GUI] [Err] [Ogre2Visual.cc:134] Cannot attach null geometry.
[GUI] [Err] [MeshDescriptor.cc:54] Mesh manager can't find mesh named [gizmo_rotate]
[GUI] [Err] [Ogre2MeshFactory.cc:566] Cannot load null mesh [gizmo_rotate]
[GUI] [Err] [Ogre2MeshFactory.cc:125] Failed to get Ogre item for [gizmo_rotate]
[GUI] [Err] [Ogre2Visual.cc:134] Cannot attach null geometry.
[GUI] [Err] [MeshDescriptor.cc:54] Mesh manager can't find mesh named [gizmo_rotate_full]
[GUI] [Err] [Ogre2MeshFactory.cc:566] Cannot load null mesh [gizmo_rotate_full]
[GUI] [Err] [Ogre2MeshFactory.cc:125] Failed to get Ogre item for [gizmo_rotate_full]
[GUI] [Err] [Ogre2Visual.cc:134] Cannot attach null geometry.
[GUI] [Err] [MeshDescriptor.cc:54] Mesh manager can't find mesh named [gizmo_rotate_handle]
[GUI] [Err] [Ogre2MeshFactory.cc:566] Cannot load null mesh [gizmo_rotate_handle]
[GUI] [Err] [Ogre2MeshFactory.cc:125] Failed to get Ogre item for [gizmo_rotate_handle]
[GUI] [Err] [Ogre2Visual.cc:134] Cannot attach null geometry.
[GUI] [Err] [MeshDescriptor.cc:54] Mesh manager can't find mesh named [gizmo_rotate_handle]
[GUI] [Err] [Ogre2MeshFactory.cc:566] Cannot load null mesh [gizmo_rotate_handle]
[GUI] [Err] [Ogre2MeshFactory.cc:125] Failed to get Ogre item for [gizmo_rotate_handle]
[GUI] [Err] [Ogre2Visual.cc:134] Cannot attach null geometry.
[GUI] [Err] [MeshDescriptor.cc:54] Mesh manager can't find mesh named [gizmo_rotate_handle]
[GUI] [Err] [Ogre2MeshFactory.cc:566] Cannot load null mesh [gizmo_rotate_handle]
[GUI] [Err] [Ogre2MeshFactory.cc:125] Failed to get Ogre item for [gizmo_rotate_handle]
[GUI] [Err] [Ogre2Visual.cc:134] Cannot attach null geometry.
```

**Comment by ahcorde** [comment]
I combined the installed `gz-garden` debs with `gz-rendering` from sources. The issue is in this library because this combination is working.

**Comment by iche033** [comment]
I reproduced this issue using the debs and summarized my finding in https://github.com/gazebosim/gz-rendering/pull/732#issuecomment-1268804972

**Comment by azeey** [comment]
Fixed by https://github.com/gazebosim/gz-common/pull/451

**Comment by aserbremen** [comment]
Will this be released for gazebo fortresss. I can't seem to rotate objects in gazebo fortress

**Comment by iche033** [comment]
a gz-common 4.7.0 release was made with that patch (fortress) on 05/17/23. Maybe try updating `libignition-common4-graphics-dev`

**Comment by aserbremen** [comment]
I tried updating `libignition-common4-graphics-dev` but it said it is already at the newest version. `gizmo_rotate` is still not available after starting e.g. `ign gazebo shapes.sdf`
