### ISSUE TITLE
Gazebo hangs at "Requesting list of world names. The server may be busy downloading resources. Please be patient."

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-sim#38]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/issues/38)) by Til Hoff (Bitbucket: [turakar](https://bitbucket.org/%7B5b5196a3-571e-4e4c-bed3-6f72e4dabba8%7D/)).**

----------------------------------------
# Description

Gazebo hangs at "Requesting list of world names. The server may be busy downloading resources. Please be patient." during start.

# Steps to Reproduce

* use Fedora 29
* compile  `assimp`, `dart` and `gflags` from source \(packages are non-existent or outdated in Fedora repos\)
* install dependencies

```shell
sudo dnf install cmake freeglut-devel ffmpeg-devel freeimage-devel gflags-devel glew-devel gts-devel ogre-devel protobuf-devel protobuf-c-devel qt5 tinyxml2-devel tinyxml-devel pkg-config protobuf-compiler python qt5-qtquickcontrols qt5-qtquickcontrols2 qt5-devel qt5-qtdeclarative-devel qt5-qtquickcontrols2-devel ruby rubygem-ronn uuid-devel libzip-devel jsoncpp-devel libcurl-devel libyaml-devel czmq-devel cppzmq-devel sqlite-devel libwebsockets-devel eigen3-devel
```

* compile `ignition` based on official installation instructions
* start Gazebo using `ign gazebo -v4`

**Expected behaviour**

Gazebo GUI starts as normal.

**Actual behaviour**

Gazebo opens an “empty frame” \(window decorations are existent, but the frame is transparent and does not have any content\). Log output:

```
[Msg] Ignition Gazebo GUI    v2.9.0
[Msg] Ignition Gazebo Server v2.9.0
[Msg] Loading default world.
[Dbg] [EntityComponentManager.cc:623] Using components of type [2251689575469537287] / [ign_gazebo_components.World].
[Dbg] [EntityComponentManager.cc:623] Using components of type [13994732549916512682] / [ign_gazebo_components.Name].
[Dbg] [EntityComponentManager.cc:623] Using components of type [12592746352568925681] / [ign_gazebo_components.Gravity].
[Dbg] [EntityComponentManager.cc:623] Using components of type [13224937992534617849] / [ign_gazebo_components.MagneticField].
[Dbg] [EntityComponentManager.cc:623] Using components of type [8753193699724811771] / [ign_gazebo_components.Wind].
[Dbg] [EntityComponentManager.cc:623] Using components of type [12173050716021724529] / [ign_gazebo_components.WorldLinearVelocity].
[Dbg] [EntityComponentManager.cc:623] Using components of type [15943768124495574352] / [ign_gazebo_components.WorldLinearVelocitySeed].
[Dbg] [EntityComponentManager.cc:623] Using components of type [3297509811873971798] / [ign_gazebo_components.ParentEntity].
[Dbg] [EntityComponentManager.cc:623] Using components of type [17100615127981600159] / [ign_gazebo_components.Scene].
[Dbg] [EntityComponentManager.cc:623] Using components of type [8064491505919932473] / [ign_gazebo_components.Level].
[Dbg] [EntityComponentManager.cc:623] Using components of type [2668898242563798256] / [ign_gazebo_components.DefaultLevel].
[Dbg] [EntityComponentManager.cc:623] Using components of type [11371360182141354106] / [ign_gazebo_components.LevelEntityNames].
[Dbg] [SimulationRunner.cc:688] Loaded system [ignition::gazebo::systems::SceneBroadcaster] for entity [1]
QSettings::value: Empty key passed
QSettings::value: Empty key passed
[Dbg] [Application.cc:87] Initializing application.
[GUI] [Dbg] [Application.cc:407] Create main window
[Dbg] [SimulationRunner.cc:688] Loaded system [ignition::gazebo::systems::Physics] for entity [1]
[Msg] Create service on [/world/default/create]
[Msg] Remove service on [/world/default/remove]
[Msg] Pose service on [/world/default/set_pose]
[Dbg] [SimulationRunner.cc:688] Loaded system [ignition::gazebo::systems::UserCommands] for entity [1]
[Msg] Loaded level [3]
[Msg] Serving GUI information on [/world/default/gui/info]
[Msg] World [default] initialized with [default_physics] physics profile.
[GUI] [Wrn] [Application.cc:649] [QT] file:///usr/lib64/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
[GUI] [Wrn] [Application.cc:649] [QT] file:///usr/lib64/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain", "applicationName")
[GUI] [Wrn] [Application.cc:649] [QT] file:///usr/lib64/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
[GUI] [Wrn] [Application.cc:649] [QT] file:///usr/lib64/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain", "applicationName")
[GUI] [Msg] Loading config [/home/t/projects/debris/approach-simulator/ignitionrobotics/install/share/ignition/ignition-gazebo2/gui/gui.config]
[GUI] [Dbg] [Application.cc:266] Loading window config
[GUI] [Dbg] [Application.cc:421] Applying config
[GUI] [Wrn] [Application.cc:649] [QT] file:///usr/lib64/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
[GUI] [Wrn] [Application.cc:649] [QT] file:///usr/lib64/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain", "applicationName")
[GUI] [Wrn] [Application.cc:649] [QT] file:///usr/lib64/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
[GUI] [Wrn] [Application.cc:649] [QT] file:///usr/lib64/qt5/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain", "applicationName")
[GUI] [Dbg] [ign.cc:227] Requesting list of world names. The server may be busy downloading resources. Please be patient.
[Msg] Found no publishers on /stats, adding root stats topic
[Msg] Found no publishers on /clock, adding root clock topic
[Dbg] [SimulationRunner.cc:343] Creating PostUpdate worker threads: 2
[Dbg] [SimulationRunner.cc:356] Creating postupdate worker thread (0)
[Msg] Serving scene information on [/world/default/scene/info]
[Msg] Serving graph information on [/world/default/scene/graph]
[Msg] Serving full state on [/world/default/state]
[Msg] Publishing scene information on [/world/default/scene/info]
[Msg] Publishing entity deletions on [/world/default/scene/deletion]
[Msg] Publishing state changes on [/world/default/state]
[Msg] Publishing pose messages on [/world/default/pose/info]
[Msg] Publishing dynamic pose messages on [/world/default/dynamic_pose/info]
[GUI] [Dbg] [ign.cc:227] Requesting list of world names. The server may be busy downloading resources. Please be patient.
[GUI] [Dbg] [ign.cc:227] Requesting list of world names. The server may be busy downloading resources. Please be patient.
```

The last line is repeatedly print for over one hour.

# Versions

* Fedora 29
* source install \(for details see above\)
* latest ignition

# Additional information

* I can access [https://app.ignitionrobotics.org/fuel](https://app.ignitionrobotics.org/fuel) using my web browser
* I have a good internet connection
* Gazebo does not seem to use >50kB/s bandwidth \(my network provides a bandwidth of at least >1MB/s\)

‌

**Thank you for sharing this great software :slight_smile:**

**Comment by devashishRaj** [comment]
i am facing same on mac but on wsl2 using ubuntu 22 i fixed this issue via enabling multicast .
https://docs.ros.org/en/rolling/How-To-Guides/Installation-Troubleshooting.html

**Comment by vivekvardhan-god** [comment]
Disabling the firewall using sudo ufw disable worked for me

**Comment by McGrady-175** [comment]
> 使用 sudo ufw disable 禁用防火墙对我有用

this method is useful for me!

**Comment by Talkative-Banana** [comment]
> Disabling the firewall using sudo ufw disable worked for me

Thanks this worked!

**Comment by iameijaz** [comment]
> Disabling the firewall using sudo ufw disable worked for me

This also worked for me in Ubuntu 24.04 for Gazebo Harmonic 


Is there anyone for which this issue still remains? If yes then share the steps to reproduce, I will look into it.

**Comment by AJedancov** [comment]
> Is there anyone for which this issue still remains? If yes then share the steps to reproduce, I will look into it.

I’ve also encountered the problem described earlier: continuously repeating "GUI requesting list of world names. The server may be busy downloading resources. Please be patient.".

**Environment:**
Ubuntu: 24.04
ROS 2: Jazzy
Gazebo Sim: 8.11.0


**Steps to reproduce:**
1. Install Gazebo
I followed the instructions from [Installing Gazebo with ROS](https://gazebosim.org/docs/jetty/ros_installation/):
```bash
sudo apt-get install ros-${ROS_DISTRO}-ros-gz
```

2.  Run the simulation without specifying a world and with detailed output:
```bash
gz sim -v 4
```

I’d appreciate it if one of the maintainers could take a look at this problem. Please let me know if you need any further information that might be helpful.

UPD
Instead of disabling the firewall, the following solution worked for me:
```bash
export GZ_IP=127.0.0.1
```
In case anyone needs to quickly solve the same problem.
